name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v5
        with:
            go-version: "1.23.0"

      - name: Build client binary
        run: |
          go build -o server ./cmd/server/

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for server
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peril/server:latest
          push: true

  build-client-binary: # This job builds the client binary but does not publish it anywhere yet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build client binary
        run: |
          go build -o client ./cmd/client/